version: "3.3"

services:
  backend:
    build: ../backend/it_one/
    volumes:
      - ~/.postgresql:~/.postgresql
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
