version: "3.3"

services:
  backend:
    build: ./
    volumes:
      - ~/.postgresql/root.crt:/root/.postgresql/root.crt
    env_file: ./src/main/resources/.env
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
