version: "3.3"

volumes:
  pg_data:

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build: ../backend/it_one/
    restart: always
    depends_on:
      - postgres
  frontend:
    restart: no
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/usr/share/nginx/html/
    depends_on:
      - frontend
      - backend
