version: "3.3"

services:
  backend:
    image: littump/backend_project:latest
    restart: always
  frontend:
    restart: no
    image: littump/frontend_project:latest
    volumes:
      - ../frontend/:/app/result_build/
    env_file: ../frontend/.env
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/usr/share/nginx/html/
    depends_on:
      - frontend
