name: Workflow

on:
  push:
    branches:
      - STABLE

jobs:

  build_and_push_to_docker_hub:
    name: Build and push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend_project:latest

      - name: Push python backend file docker to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/it_one
          file: ./backend/it_one/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend_project:latest

  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSPHRASE }}
          script: |
            cd ../home/littump/site
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d

  deploy-2:
    name: Deploy image
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USER2 }}
          password: ${{ secrets.PASSPHRASE2 }}
          script: |
            cd site
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d

  deploy-3:
    name: Deploy image
    runs-on: ubuntu-latest
    needs: deploy-2
    steps:
      - name: deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST3 }}
          username: ${{ secrets.USER3 }}
          password: ${{ secrets.PASSPHRASE3 }}
          script: |
            cd site
            sudo docker compose pull
            sudo docker compose down
            sudo docker compose up -d

  send_message_telegram:
    name: message in tg
    runs-on: ubuntu-latest
    needs: deploy-3
    steps:
      - name: sms
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Деплой dubna успешно выполнен!
